backend:
  name: git-gateway
  branch: principal  # ou main, dependendo do seu repositório

media_folder: "imagens"        # pasta onde as imagens serão salvas
public_folder: "/imagens"       # caminho público usado no site
media_library:
  name: uploadcare              # pode ser uploadcare ou cloudinary

collections:
  - name: "produtos"
    label: "Produtos"
    files:
      - file: "content/produtos.json"
        label: "Lista de Produtos"
        name: "lista"
        fields:
          - label: "Produtos"
            name: "produtos"
            widget: "list"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "price", widget: "number" }
              - { label: "Categoria", name: "categoria", widget: "select", options: ["burger", "bebida"] }
              - { label: "Ingredientes", name: "ingredientes", widget: "string", required: false }
              - { label: "Imagem", name: "image", widget: "image" }
