backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true

    extension: "json"
    format: "json"

    slug: "{{slug}}"

    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Pre√ßo", name: "price", widget: "number", value_type: "float" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
