backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "produtos"
    label: "Produtos"
    file: "content/produtos.json"
    format: "json"
    fields:
      - label: "Produtos"
        name: "produtos"
        widget: "list"
        fields:
          - { label: "Código", name: "codigo", widget: "string" }
          - { label: "Nome", name: "title", widget: "string" }
          - { label: "Preço", name: "price", widget: "number" }
          - { label: "Categoria", name: "categoria", widget: "select", options: ["burger","bebida"] }
          - { label: "Ingredientes", name: "ingredientes", widget: "string", required: false }
          - { label: "Imagem", name: "image", widget: "image" }

  - name: "status"
    label: "Status da Loja"
    file: "content/status.json"
    format: "json"
    fields:
      - { label: "Loja Aberta", name: "aberto", widget: "boolean" }
      - { label: "Mensagem Fechado", name: "mensagem", widget: "string" }
