backend:
  name: git-gateway
  branch: main   # ou master (confira no GitHub)

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Pre√ßo", name: "price", widget: "number" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
